name: Run Tests

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: push

jobs:
  test: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [23.2]
        elixir: [1.11.2]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with: 
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}

    - name: Cache Elixir deps
      uses: actions/cache@v1
      id: deps-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Cache Elixir _build
      uses: actions/cache@v1
      id: build-cache
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }} 

    - name: Install deps
      run: |
        mix deps.get
        
    - name: Run Tests
      run: |
        mix coveralls.github